### ISSUE TITLE
dwm-status2d fails to work against current git master

### ISSUE THREAD

**Issue by pickfire** [sipi/dwm-status2d#1]

**Comment by sipi** [comment]
Yes, the patch works with the revision 35db6d as indicated by his name (dwm-r35db6d-status2d.diff). I will build a new patch for this last revision but it is not trivial, the last commit impacts the code of this patch.

**Comment by pickfire** [comment]
Yeah, maybe you could use the new functions in `drw.c`.

**Comment by pickfire** [comment]
I think I have created a broken patch that works but doesn't display the title and status correctly.

http://ix.io/lJL

**Comment by sipi** [comment]
I will test this patch as soon as possible. 
But your diff is only about the dwm.c file and I'm sure that the main modifications have to be done in the drw.c file.

**Comment by pickfire** [comment]
They had already done the drw.c which is `drw_text`, `drw_rect` and `drw_setscheme`. Only `drw_setscheme` is different from your old `x_setcolor` which takes **ClrScheme** instead of **Clr** as the parameter.

It seems like they are going to do `dwmutils` that can change the color on the fly. Look at the *slcon2* video.
