### ISSUE TITLE
update for dwm 6.1

### ISSUE THREAD

**Issue by Lesik** [sipi/dwm-status2d#2]
Hey,

I was wondering whether you could make this patch work for dwm 6.1.

I tried modifying the patch myself, but there are too many changes in drw.c in 6.1.

**Comment by sipi** [comment]
Hi,
I have not seen there is a new release, I will try to update the patch for this one. But, as you noticed there is lot of changes that make the update non-trivial. So, I can't promise you to do it quickly.

**Comment by Lesik** [comment]
No problem, take your time. Please comment here when you have ported it.

**Comment by sipi** [comment]
I will do it

**Comment by sipi** [comment]
There is now a version for 6.2 and 6.3, so I close.

**Comment by Lesik** [comment]
Thanks @sipi!
