### ISSUE TITLE
[Feature request] set background color

### ISSUE THREAD

**Issue by GasparVardanyan** [sipi/dwm-status2d#4]

**Comment by sipi** [comment]
Hi,
thank you for your interest in the project.
I think I understand your request however can you add some details…

Do you want to set the background on the full width or only on the a subpart ?
do you have a syntax suggestion?

thanks

**Comment by GasparVardanyan** [comment]
Something like ^c#FF0000^. For example: ^b#FF0000^
There is a newer version of your patch: https://dwm.suckless.org/patches/status2d/

**Comment by sipi** [comment]
It has been introduce in https://github.com/sipi/dwm-status2d/blob/master/dwm-status2d-6.2.diff by @lhark
